# Generated by Django 3.2.8 on 2021-11-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_sreg_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='rno',
        ),
    ]
