# Generated by Django 3.2.8 on 2021-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_allocation_rno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='htid',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='stid',
        ),
        migrations.AddField(
            model_name='allocation',
            name='bdate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
