# Generated by Django 3.2.8 on 2021-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211121_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='bdate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
