# Generated by Django 3.2.8 on 2021-11-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20211124_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allocation',
        ),
    ]
