# Generated by Django 3.2.8 on 2021-11-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_delete_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('htid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.hreg')),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.sreg')),
            ],
        ),
    ]
