# Generated by Django 3.2.8 on 2021-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bdate',
            field=models.CharField(max_length=40),
        ),
    ]
