# Generated by Django 3.2.8 on 2021-11-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_booking_bdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
