# Generated by Django 3.2.8 on 2021-12-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
